realestate/listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('property/<int:property_id>', views.detail, name='detail'),
    path('for-sale', views.for_sale, name='for-sale'),
    path('for-rent', views.for_rent, name='for-rent'),
    path('contact', views.contact, name='contact'),
    path('events', views.events, name='events'),
    path('event-detail', views.event_detail, name='event-detail'),
    path('event/<int:event_id>', views.event_detail, name='event-detail'),
    path('search', views.search, name='search'),
]

realestate/realestate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('listings.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

realestate/listings/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
# from django.utils.timezone import now
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import gettext as _


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Property(models.Model):
    PROPERTY_TYPE = (
        ('For Sale', _('For Sale')),
        ('For Rent', _('For Rent')),
    )
    title = models.CharField(max_length=250)
    category = models.ForeignKey('Category', on_delete=models.DO_NOTHING)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    # type = models.BooleanField(default=False)
    # property_type = models.BooleanField(default=0)
    property_type = models.CharField(max_length=10, choices=PROPERTY_TYPE, verbose_name=_('property_type'))
    created = models.DateTimeField(auto_now_add=True)
    published = models.DateTimeField(timezone.now())
    updated = models.DateTimeField(auto_now=True)
    photo_main = models.ImageField(upload_to='pics')
    photo1 = models.ImageField(upload_to='pics', blank=True)
    photo2 = models.ImageField(upload_to='pics', blank=True)
    photo3 = models.ImageField(upload_to='pics', blank=True)
    photo4 = models.ImageField(upload_to='pics', blank=True)
    photo5 = models.ImageField(upload_to='pics', blank=True)
    photo6 = models.ImageField(upload_to='pics', blank=True)
    photo7 = models.ImageField(upload_to='pics', blank=True)
    photo8 = models.ImageField(upload_to='pics', blank=True)
    photo9 = models.ImageField(upload_to='pics', blank=True)

    class Meta:
        verbose_name = 'property'
        verbose_name_plural = 'properties'

    def __str__(self):
        return self.title


class Events(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    photo = models.FileField(upload_to='pics/events')
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    class Meta:
        verbose_name = 'event'
        verbose_name_plural = 'events'

    def __str__(self):
        return self.title


class About(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    description = RichTextUploadingField(blank=True)


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=15)
    subject = models.CharField(max_length=50)
    message = models.TextField()

    def __str__(self):
        return self.name

realestate/listings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Property, About, Contact, Events
from django.core.paginator import Paginator
from django.contrib import messages


# Create your views here.
def index(request, category_slug=None):
    category = None
    categories = Category.objects.filter(name='Top Listings', slug='top-listings')
    properties = Property.objects.filter(available=True, category__name='Top Listings')
    featured = Category.objects.filter(name='Featured Properties', slug='featured-properties')
    featured_properties = Property.objects.filter(available=True, category__name='Featured Properties')
    abouts = About.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        properties = properties.filter(category=categories)
        featured = get_object_or_404(Category, slug=category_slug)
        featured_properties = featured_properties.filter(category=featured)
    context = {'properties': properties,
               'categories': categories,
               'featured_properties': featured_properties,
               'featured': featured,
               'category': category,
               'abouts': abouts
               }
    return render(request, 'listing/index.html', context)


def about(request):
    return render(request, 'listing/about.html')


def detail(request, property_id):
    properties = get_object_or_404(Property, pk=property_id)
    context = {
        'properties': properties,
    }
    return render(request, 'listing/detail.html', context)


def for_sale(request):
    property_list = Property.objects.filter(property_type='For Sale')
    paginator = Paginator(property_list, 6)
    page = request.GET.get('page')
    properties = paginator.get_page(page)
    context = {
        'properties': properties,
    }
    return render(request, 'listing/for-sale.html', context)


def for_rent(request):
    property_list = Property.objects.filter(property_type='For Rent')
    paginator = Paginator(property_list, 6)
    page = request.GET.get('page')
    properties = paginator.get_page(page)
    context = {
        'properties': properties,
    }
    return render(request, 'listing/for-rent.html', context)


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        subject = request.POST['subject']
        message = request.POST['message']
        contact = Contact(name=name, email=email, phone=phone, subject=subject, message=message)
        contact.save()
        messages.success(request, 'Your message has been submitted.')
    return render(request, 'listing/contact.html')


def events(request):
    event_list = Events.objects.all()
    paginator = Paginator(event_list, 4)
    page = request.GET.get('page')
    events = paginator.get_page(page)
    context = {
        'events': events,
    }
    return render(request, 'listing/events.html', context)


def event_detail(request, event_id):
    event = get_object_or_404(Events, pk=event_id)
    context = {
        'event': event,
    }
    return render(request, 'listing/event-detail.html', context)


def search(request):
    queryset_list = Property.objects.all()
    paginator = Paginator(queryset_list, 4)
    page = request.GET.get('page')
    listings = paginator.get_page(page)

    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(title__icontains=keywords)

    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(price__exact=price)

    if 'property_type' in request.GET:
        property_type = request.GET['property_type']
        if property_type:
            queryset_list = queryset_list.filter(property_type__exact=property_type)

    context = {
        'properties': queryset_list,
        'values': request.GET,
        'listings': listings,
    }

    return render(request, 'listing/search.html', context)

realestate/listings/templates/listing/about.html
{% extends 'listing/base.html' %}
{% block title %}About{% endblock %}
{% block body %}
    {% load static %}
    <div class="hero-wrap" style="background-image: url({% static 'listing/images/bg_1.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>About</span>
                    </p>
                    <h1 class="mb-3 bread">About</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-section ftc-no-pb">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-md-5 p-md-5 img img-2 d-flex justify-content-center align-items-center"
                     style="background-image: url(images/about.jpg);">
                    <a href="https://vimeo.com/45830194"
                       class="icon popup-vimeo d-flex justify-content-center align-items-center">
                        <span class="icon-play"></span>
                    </a>
                </div>
                <div class="col-md-7 wrap-about pb-md-5 ftco-animate">
                    <div class="heading-section heading-section-wo-line mb-5 pl-md-5">
                        <div class="pl-md-5 ml-md-5">
                            <span class="subheading">Company Overview</span>
                            <h2 class="mb-4">Learned about the Law</h2>
                        </div>
                    </div>
                    <div class="pl-md-5 ml-md-5 mb-5">
                        <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it
                            would have been rewritten a thousand times and everything that was left from its origin
                            would be the word "and" and the Little Blind Text should turn around and return to its own,
                            safe country. But nothing the copy said could convince her and so it didn’t take long until
                            a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged
                            her into their agency, where they abused her for their.</p>
                        <p>When she reached the first hills of the Italic Mountains, she had a last view back on the
                            skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of
                            her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she
                            continued her way.</p>
                        <p><a href="#" class="btn-custom">Learn More <span class="ion-ios-arrow-forward"></span></a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

realestate/listings/templates/listing/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {#    {% load static %}#}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'listing/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'listing/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'listing/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'listing/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'listing/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'listing/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'listing/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'listing/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'listing/css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'listing/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'listing/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'listing/css/style.css' %}">

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
</head>
<body>
<div class="top">
    <div class="container">
        <div class="row d-flex align-items-center">
            <div class="col">
                <p class="social d-flex">
                    <a href="#"><span class="icon-facebook"></span></a>
                    <a href="#"><span class="icon-twitter"></span></a>
                    <a href="#"><span class="icon-google"></span></a>
                    <a href="#"><span class="icon-pinterest"></span></a>
                </p>
            </div>
            <div class="col d-flex justify-content-end">
                <p class="num"><span class="icon-phone"></span> + 1700 12345 6789</p>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">Royal<span>estate</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'listings:index' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'listings:about' %}" class="nav-link">About</a></li>
                <li class="nav-item"><a href="{% url 'listings:for-sale' %}" class="nav-link">For Sale</a></li>
{#                <li class="nav-item"><a href="#" class="nav-link">Land on Sale</a></li>#}
                <li class="nav-item"><a href="{% url 'listings:for-rent' %}" class="nav-link">For Rent</a></li>
                <li class="nav-item"><a href="{% url 'listings:events' %}" class="nav-link">Events</a></li>
                {#                <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>#}
                <li class="nav-item"><a href="{% url 'listings:contact' %} " class="nav-link">Contact</a></li>
                {#                <li class="nav-item cta"><a href="contact.html" class="nav-link ml-lg-2"><span class="icon-user"></span>#}
                {#                    Sign-In</a></li>#}
                {#                <li class="nav-item cta cta-colored"><a href="contact.html" class="nav-link"><span#}
                {#                        class="icon-pencil"></span> Sign-Up</a></li>#}

            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->
{% block body %}
{% endblock %}
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Royalestate</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Buy</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Home For Sale</a></li>
                        <li><a href="#" class="py-2 d-block">Open Houses</a></li>
                        <li><a href="#" class="py-2 d-block">New Listing</a></li>
                        <li><a href="#" class="py-2 d-block">Recently Reduce</a></li>
                        <li><a href="#" class="py-2 d-block">Off-Market Homes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Sell</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Sell Your Home</a></li>
                        <li><a href="#" class="py-2 d-block">Get A Home Valuation</a></li>
                        <li><a href="#" class="py-2 d-block">Local Home Prices</a></li>
                        <li><a href="#" class="py-2 d-block">Guides &amp; Rules</a></li>
                        <li><a href="#" class="py-2 d-block">Others</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This website is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Real Estate Company</a>
                    </p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


<script src="{% static 'listing/js/jquery.min.js' %}"></script>
<script src="{% static 'listing/js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'listing/js/popper.min.js' %}"></script>
<script src="{% static 'listing/js/bootstrap.min.js' %}"></script>
<script src="{% static 'listing/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'listing/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'listing/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'listing/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'listing/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'listing/js/aos.js' %}"></script>
<script src="{% static 'listing/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'listing/js/bootstrap-datepicker.js' %}"></script>
{#<script src="{% static 'listing/js/jquery.timepicker.min.js' %}"></script>#}
<script src="{% static 'listing/js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'listing/js/google-map.js' %}"></script>
<script src="{% static 'listing/js/main.js' %}"></script>

</body>
</html>

realestate/listings/templates/listing/event-detail.html
{% extends 'listing/base.html' %}
{% block title %}Real Estate - Event Detail Page{% endblock %}
{% block body %}
    {% load static %}
    <div class="hero-wrap" style="background-image: url({% static 'listing/images/bg_1.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                            class="mr-2"><a href="{% url 'listings:index' %}">Home</a></span> <span class="mr-2"><a
                            href="{% url 'listings:events' %}">Events</a></span> <span>Event-Details</span></p>
                    <h1 class="mb-3 bread">Event-Details</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 ftco-animate">
                    <h2 class="mb-3">{{ event.title }}</h2>
                    <p>{{ event.description }}</p>
                    <img src="{{ event.photo.url }}" alt="" class="img-fluid">
                    </p>
                </div>
            </div> <!-- .col-md-8 -->
        </div>
    </section> <!-- .section -->
{% endblock %}

realestate/listings/templates/listing/search.html
{% extends 'listing/base.html' %}
{% block title %}Royal Estate - Search Results{% endblock %}
{% block body %}
    {% load static %}
    <div class="hero-wrap" style="background-image: url({% static 'listing/images/bg_1.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'listings:index' %}">Home</a></span>
                        <span>Property</span>
                    </p>
                    <h1 class="mb-3 bread">Property</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-search">
        <div class="container">
            <div class="row">
                <div class="col-md-12 search-wrap">
                    <h2 class="heading h5 d-flex align-items-center pr-4"><span class="ion-ios-search mr-3"></span>
                        Search
                        Property</h2>
                    <form action="{% url 'listings:search' %}" class="search-property">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md align-items-end">
                                <div class="form-group">
                                    <label for="keywords">Keywords</label>
                                    <div class="form-field">
                                        <div class="icon"><span class="icon-my_location"></span></div>
                                        <input type="text" name="keywords" class="form-control" placeholder="Keyword"
                                               value="{{ values.keywords }}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md align-items-end">
                                <div class="form-group">
                                    <label for="Price">Price</label>
                                    <div class="form-field">
                                        <div class="icon"><span class="icon-my_location"></span></div>
                                        <input type="text" name="price" class="form-control" placeholder="Price"
                                               value="{{ values.price }}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md align-items-end">
                                <div class="form-group">
                                    <label for="property_type">Property Type</label>
                                    <div class="form-field">
                                        <div class="select-wrap">
                                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                            <select name="property_type" id="property_type" class="form-control">
                                                {% for property in properties %}
                                                    <option value="For Sale">{{ property.property_type }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md align-self-end">
                                <div class="form-group">
                                    <div class="form-field">
                                        <input type="submit" value="Search" class="form-control btn btn-primary">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>


    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row">
                {% if  properties %}
                    {% for property in properties %}
                        <div class="col-md-4 ftco-animate">

                            <div class="properties">

                                <a href="{% url 'listings:detail' property.id %}"
                                   class="img img-2 d-flex justify-content-center align-items-center"
                                   style="background-image: url({{ property.photo_main.url }});">
                                </a>
                                <div class="text p-3">
                                    {% if property.property_type %}
                                        <span class="status sale">{{ property.get_property_type_display }}</span>
                                    {% endif %}
                                    <div class="d-flex">
                                        <div class="one">
                                            <h3>
                                                <a href="{% url 'listings:detail' property.id %}">{{ property.title }}</a>
                                            </h3>
                                        </div>
                                        <div class="two">
                                            <span class="price">{{ property.price }}</span>
                                        </div>
                                    </div>
                                    {#                                <p>{{ property.description }}</p>#}
                                </div>

                            </div>

                        </div>
                    {% endfor %}
                {% else %}
                    <div class="col-md-12">
                        <p>No Properties Available</p>
                    </div>
                {% endif %}
            </div>
            <div class="pagination row mt-3">
                <div class="col text-center">
                <span class="step-links">
                     {% if listings.has_previous %}
                         <a class="btn btn-outline-info mb-4" href="?page=1">&laquo; First</a>
                         <a class="btn btn-outline-info mb-4" href="?page={{ listings.previous_page_number }}">Previous</a>
                     {% endif %}
                    {#                    <span class="current">#}
{#                        Page {{ properties.number }} of {{ properties.paginator.num_pages }}.#}
{#                    </span>#}
                    {% for num in listings.paginator.page_range %}
                        {% if listings.number == num %}
                            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                        {% elif num > listings.number|add:'-3' and num < listings.number|add:'3' %}
                            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if listings.has_next %}
                        <a class="btn btn-outline-info mb-4" href="?page={{ listings.next_page_number }}">Next</a>
                        <a class="btn btn-outline-info mb-4" href="?page={{ listings.paginator.num_pages }}">Last &raquo;</a>
                    {% endif %}
                </span>
                </div>
            </div>
            {#            <div class="row mt-5">#}
            {#                <div class="col text-center">#}
            {#                    <div class="block-27">#}
            {#                        <ul>#}
            {#                            <li><a href="#">&lt;</a></li>#}
            {#                            <li class="active"><span>1</span></li>#}
            {#                            <li><a href="#">2</a></li>#}
            {#                            <li><a href="#">3</a></li>#}
            {#                            <li><a href="#">4</a></li>#}
            {#                            <li><a href="#">5</a></li>#}
            {#                            <li><a href="#">&gt;</a></li>#}
            {#                        </ul>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </div>#}
        </div>
    </section>
{% endblock %}